---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: sundayos
description: My sunday os
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 44

modules:
  - from-file: rpmostree.yml
  - from-file: dnf.yml
  # - from-file: script.yml
  # - from-file: files.yml
  - from-file: font.yml
  - from-file: flatpak.yml
  - from-file: os-release.yml

  - type: signing
